heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:

  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: mykey
    constraints:
      - custom_constraint: nova.keypair

  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default: inf4410-net

resources:
  server:
      type: OS::Nova::Server
      properties:
        key_name: { get_param: key_name }
        image: { get_param: image }
        flavor: { get_param: flavor }
        networks:
          - network: { get_param: subnet_id }
        user_data: |
          #!/bin/bash
          wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
          python server.py &

  #mypool:
      #type: OS::Neutron::Pool
      #A completer

  #loadbalancer:
      #type: OS::Neutron::LoadBalancer
      #A completer

  #monitor:
      #type: OS::Neutron::HealthMonitor
      #properties:
      #A completer


#outputs:
  #pool_ip_address:
    #value: {get_attr: [server]}
    #description: The IP address of the load balancing pool
